#include "protocol_items.h" // IWYU pragma: keep

const SubGhzProtocol* const subghz_protocol_registry_items[] = {
    &subghz_protocol_gate_tx,       &subghz_protocol_keeloq,
    &subghz_protocol_nice_flo,      &subghz_protocol_came,
    &subghz_protocol_faac_slh,      &subghz_protocol_nice_flor_s,
    &subghz_protocol_came_twee,     &subghz_protocol_came_atomo,
    &subghz_protocol_nero_sketch,   &subghz_protocol_ido,
    &subghz_protocol_hormann,       &subghz_protocol_nero_radio,
    &subghz_protocol_somfy_telis,   &subghz_protocol_somfy_keytis,
    &subghz_protocol_princeton,     &subghz_protocol_raw,
    &subghz_protocol_linear,        &subghz_protocol_secplus_v2,
    &subghz_protocol_secplus_v1,    &subghz_protocol_megacode,
    &subghz_protocol_holtek,        &subghz_protocol_chamb_code,
    &subghz_protocol_power_smart,   &subghz_protocol_marantec,
    &subghz_protocol_bett,          &subghz_protocol_doitrand,
    &subghz_protocol_phoenix_v2,    &subghz_protocol_honeywell_wdb,
    &subghz_protocol_magellan,      &subghz_protocol_intertechno_v3,
    &subghz_protocol_clemsa,        &subghz_protocol_ansonic,
    &subghz_protocol_smc5326,       &subghz_protocol_holtek_th12x,
    &subghz_protocol_linear_delta3, &subghz_protocol_dooya,
    &subghz_protocol_alutech_at_4n, &subghz_protocol_kinggates_stylo_4k,
    &subghz_protocol_bin_raw,       &subghz_protocol_mastercode,
    &subghz_protocol_honeywell,     &subghz_protocol_legrand,
    &subghz_protocol_dickert_mahs,  &subghz_protocol_gangqi,
    &subghz_protocol_marantec24,    &subghz_protocol_hollarm,
    &subghz_protocol_hay21,         &subghz_protocol_revers_rb2,
    &subghz_protocol_feron,         &subghz_protocol_roger,
    &subghz_protocol_elplast,       &subghz_protocol_treadmill37,
    &subghz_protocol_beninca_arc,   &subghz_protocol_jarolift,
    &subghz_protocol_ditec_gol4,    &subghz_protocol_keyfinder,
    // Vehicle protocols
    &subghz_protocol_audi_v1,      // &subghz_protocol_audi_v2,
//    &subghz_protocol_bmw_v2,        &subghz_protocol_bmw_v3,
////    &subghz_protocol_chevrolet_v0,  &subghz_protocol_ducato_v0,
//    &subghz_protocol_fiat_v0,       &subghz_protocol_fiat,
//    &subghz_protocol_ford_v0,       &subghz_protocol_mazda_v0,
//    &subghz_protocol_ford_v1,       &subghz_protocol_ford_v2,
//    &subghz_protocol_honda_v0,      &subghz_protocol_honda_v1,
//    &subghz_protocol_honda_v2_v3,   &subghz_protocol_honda_v4,
//    &subghz_protocol_honda_v5,      &subghz_protocol_honda_v6,
//    &subghz_protocol_kia_v0,        &subghz_protocol_kia_v1,
//    &subghz_protocol_kia_v2,        &subghz_protocol_kia_v3_v4,
//    &subghz_protocol_kia_v5,        &subghz_protocol_kia_v6,
//    &subghz_protocol_mercedes_v0,   &subghz_protocol_psa,
//    &subghz_protocol_renault,       &subghz_protocol_subaru,
//    &subghz_protocol_suzuki_v0,     //&subghz_protocol_unknown_v0,
//    &subghz_protocol_vag,
};

const SubGhzProtocolRegistry subghz_protocol_registry = {
    .items = subghz_protocol_registry_items,
    .size = COUNT_OF(subghz_protocol_registry_items)};
